### ISSUE TITLE
Can't execute on Windows: Error: Cannot find module 'tcpfwd-maxconc-pmb'

### ISSUE THREAD

**Issue by CobusKruger** [mk-pmb/tcpfwd-maxconc-pmb-node#1]
Hi,

I was so excited when I found this, but I'm having trouble executing it.

This is the example given:

`$ nodejs -r tcpfwd-maxconc-pmb -e 0 -- max_conc=5`

I'm running on Windows and there is no `nodejs` command, so I assumed the reference was to `node.exe`. It makes sense, because then -r would require the module. Unfortunately, running 

`node -r tcpfwd-maxconc-pmb`

Gives me an error:
```

module.js:471
    throw err;
    ^

Error: Cannot find module 'tcpfwd-maxconc-pmb'
    at Function.Module._resolveFilename (module.js:469:1
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at module.js:669:12
    at Array.forEach (native)
    at Function.Module._preloadModules (module.js:668:12
    at preloadModules (bootstrap_node.js:362:38)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:504:3

```

**Comment by mk-pmb** [comment]
Hi, thanks for trying! :tada: I'll get a windows box and test it on the weekend. Meanwhile, please try running `tfm.js` the usual way instead with `-r`, e.g. `node.exe tfm.js -- max_conc=5 lsn_port=3200`.
